# CMake generated Testfile for 
# Source directory: /Users/billalrahimi/Desktop/Robotics/C_Template/opencv/modules/core
# Build directory: /Users/billalrahimi/Desktop/Robotics/C_Template/build_opencv/modules/core
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(opencv_test_core "/Users/billalrahimi/Desktop/Robotics/C_Template/build_opencv/bin/opencv_test_core" "--gtest_output=xml:opencv_test_core.xml")
set_tests_properties(opencv_test_core PROPERTIES  LABELS "Main;opencv_core;Accuracy" WORKING_DIRECTORY "/Users/billalrahimi/Desktop/Robotics/C_Template/build_opencv/test-reports/accuracy" _BACKTRACE_TRIPLES "/Users/billalrahimi/Desktop/Robotics/C_Template/opencv/cmake/OpenCVUtils.cmake;1640;add_test;/Users/billalrahimi/Desktop/Robotics/C_Template/opencv/cmake/OpenCVModule.cmake;1310;ocv_add_test_from_target;/Users/billalrahimi/Desktop/Robotics/C_Template/opencv/modules/core/CMakeLists.txt;117;ocv_add_accuracy_tests;/Users/billalrahimi/Desktop/Robotics/C_Template/opencv/modules/core/CMakeLists.txt;0;")
add_test(opencv_perf_core "/Users/billalrahimi/Desktop/Robotics/C_Template/build_opencv/bin/opencv_perf_core" "--gtest_output=xml:opencv_perf_core.xml")
set_tests_properties(opencv_perf_core PROPERTIES  LABELS "Main;opencv_core;Performance" WORKING_DIRECTORY "/Users/billalrahimi/Desktop/Robotics/C_Template/build_opencv/test-reports/performance" _BACKTRACE_TRIPLES "/Users/billalrahimi/Desktop/Robotics/C_Template/opencv/cmake/OpenCVUtils.cmake;1640;add_test;/Users/billalrahimi/Desktop/Robotics/C_Template/opencv/cmake/OpenCVModule.cmake;1212;ocv_add_test_from_target;/Users/billalrahimi/Desktop/Robotics/C_Template/opencv/modules/core/CMakeLists.txt;118;ocv_add_perf_tests;/Users/billalrahimi/Desktop/Robotics/C_Template/opencv/modules/core/CMakeLists.txt;0;")
add_test(opencv_sanity_core "/Users/billalrahimi/Desktop/Robotics/C_Template/build_opencv/bin/opencv_perf_core" "--gtest_output=xml:opencv_perf_core.xml" "--perf_min_samples=1" "--perf_force_samples=1" "--perf_verify_sanity")
set_tests_properties(opencv_sanity_core PROPERTIES  LABELS "Main;opencv_core;Sanity" WORKING_DIRECTORY "/Users/billalrahimi/Desktop/Robotics/C_Template/build_opencv/test-reports/sanity" _BACKTRACE_TRIPLES "/Users/billalrahimi/Desktop/Robotics/C_Template/opencv/cmake/OpenCVUtils.cmake;1640;add_test;/Users/billalrahimi/Desktop/Robotics/C_Template/opencv/cmake/OpenCVModule.cmake;1213;ocv_add_test_from_target;/Users/billalrahimi/Desktop/Robotics/C_Template/opencv/modules/core/CMakeLists.txt;118;ocv_add_perf_tests;/Users/billalrahimi/Desktop/Robotics/C_Template/opencv/modules/core/CMakeLists.txt;0;")
