CC=g++
SRC := /Users/billalrahimi/Desktop/Robotics/C_Template/RobotArm
CFLAGS := -std=c++11
CFRAME := -framework OpenGL -framework GLUT


all: Lab

Lab:
	$(CC) $(CFLAGS) $(CFRAME) -w Lab2.cpp -o labExec

clean:
	rm -rf labExec
